project:
  type: website

website:
  sidebar:
    logo: assets/stat_bear.png
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: office-hours.qmd
        text: Office Hours
      - href: notes.qmd
        text: Notes 
      - href: slides.qmd
        text: Slides 
      - href: problem-sets.qmd
        text: Problem Sets

